kubernetes-sigs/cloud-provider-kind

- examples/loadbalancer_etp_cluster.yaml
- examples/loadbalancer_etp_local.yaml
k8s.gcr.io is deprecated. See: https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/
> examples: switch to registry.k8s.io

- Dockerfile
- README.md
- pkg/controller/controller.go
- pkg/loadbalancer/proxy.go
Allow to run ccm both inside or outside of the kind network, so it is simpler to deploy just running a docker container instead of having to run the binary
> Run CCM inside a container

- pkg/loadbalancer/proxy.go
- pkg/loadbalancer/proxy_test.go
The templating of the haproxy config was only supporting single port services
Fixes: #37
> support multiple ports on services

- pkg/constants/constants.go
- pkg/loadbalancer/server.go
- pkg/loadbalancer/server_test.go
This change truncates the loadbalancer name to 63 characters max and ensures there are no trailing dots, dashes, or underscores. 
/fixes #35
> Added name length cap for loadbalancer name

- README.md
- pkg/loadbalancer/address_windows.go
This PR was discussed in [issue 44](https://github.com/kubernetes-sigs/cloud-provider-kind/issues/44) with @aojea and contains the update we discussed together.
I have tested on Windows 11 and the changes worked fine, so this improves the Windows support to the same level as macOS.
> Add the command to add an IP to an interface on Windows

- examples/loadbalancer_affinity.yaml
- examples/loadbalancer_udp_tcp.yaml
- pkg/container/container.go
- pkg/loadbalancer/proxy.go
- pkg/loadbalancer/proxy_test.go
Switching to envoy will give us more features and also the capacity to configure remotely the loadbalancers
Fixes: #58, #57
> replace haproxy with envoy (static configuration)

- pkg/loadbalancer/server.go
cloud-provider-kind proxies all traffic rather than redirecting it, so we need to set `IPMode: Proxy` to indicate that (since `IPMode: VIP` is otherwise assumed if `IP` is set rather than `Hostname`).
(IPMode field is beta in 1.30.)
/assign @aojea
> Set correct IPMode in LoadBalancerStatus

- pkg/loadbalancer/proxy.go
- pkg/loadbalancer/server.go
This restarts the loadbalancer container when it crashes because of https://github.com/envoyproxy/envoy/issues/34195
Apparently on the restart it works fine and the test goes through.
There are a lot of hacks to deal with files and the user id for the container command is different than the one to update them, so during the restart it fails to touch the config files, since we are not worried by security on these envoys I just give them a+rw  .... the goal is to move to dynamic configuration using GRPC https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/dynamic_configuration so this hack will serve until then
> solve UDP crashes

- README.md
- compose.yml
Utilizing `docker-compose` tool can reduce the number of instructions used to deploy the cloud provider service.
> Enable docker compose

- pkg/container/container.go
- pkg/loadbalancer/proxy.go
- pkg/loadbalancer/server.go
Instead of waiting a random time do active polling to check the state of the envoy container, this will also help to detect containers restarts
> Use the envoy admin port to detect when the loadbalancer is ready to accept connections

- pkg/loadbalancer/address_darwin.go
- pkg/loadbalancer/address_other.go
- pkg/loadbalancer/address_windows.go
- pkg/loadbalancer/server.go
- pkg/loadbalancer/tunnel.go
It's an attempt to support WSL 2
It should be run with sudo like on any other platform tunnels required:
```
sudo bin/cloud-provider-kind
```
#100
> add WSL2/linux support

- pkg/loadbalancer/proxy.go
- pkg/loadbalancer/server.go
Fixes: https://github.com/kubernetes-sigs/cloud-provider-kind/issues/111
> Only enable IPv6 on loadbalancer container when the service is ipv6

- pkg/loadbalancer/proxy.go
This should fix an issue where `docker.io` might not be in the list of `unqualified-search-registries` when using Podman.
This _might_ be the root cause for #116.
> Use fully qualified image name for envoy proxy image

- cmd/app.go
- pkg/config/config.go
- pkg/controller/controller.go
- pkg/loadbalancer/proxy.go
- pkg/loadbalancer/server.go
These are these combinations
- Two type of platforms: containers reachable (Linux) or not reachable from host (Mac, Windows they run in a VM )
- Two type of deployments: cloud-provider-kind as a container or as a proces.
1. Containers Reachable and KCCM Process: Direct (Linux) (autodetected)
2. Containers Reachable and KCCM container: Direct (Linux) (autodetected)
3. Containers Not Reachable and KCCM Process: Tunnel (Mac, Windows, WSL2) (autodetected)
4. Containers Not Reachable and KCCM Container: Portmap (Mac, Windows, WSL2) (set via flag)
Fixes: #109
> support different platforms and connectivity scenarios

- cmd/app.go
On macOS, cloud-provider-kind requires sudo because it relies on Docker's port mapping to expose the LoadBalancer's IP and ports to the host, and this network configuration requires root privileges. issue: https://github.com/kubernetes-sigs/cloud-provider-kind/issues/117
> Prompt user if process running on Mac not under sudo

- OWNERS
This adds my handle as one of the reviewers for the repo. Happy to help where I can.
/assign aojea
> Add stmcginnis as a reviewer

- cloudbuild.yaml
The image will be promoted to `registry.k8s.io/cloud-provider-kind/cloud-controller-manager:vX.Y.Z`
> publish cloud-provider kind to the correct registry

- Dockerfile
see discussion in https://github.com/kubernetes-sigs/cloud-provider-kind/issues/171, not sure if this is a complete fix but it should help, we avoid qemu entirely
> docker: cross compile binary

- README.md
This PR address two issues about the README raised in https://github.com/kubernetes-sigs/cloud-provider-kind/issues/144:
* The wording around removing the `node.kubernetes.io/exclude-from-external-load-balancers` label can be confusing for less experienced users.
* This PR adds additional detail and links to external documentation.
* The provided command to remove the label from the default kind node can be difficult to run for less experienced users.
* This PR removes the output line, so the command can be copied directly.
Also included are:
* Small formatting changes to the README to bring it in line with standard markdown formatting guidelines.
* Additional section headings around the referenced section to more clearly delineate logical areas.
Happy to make any required adjustments. …
> Fix exclude label docs

- .github/workflows/k8s.yml
- pkg/controller/controller.go
- pkg/controller/http.go
- pkg/controller/http_test.go
Improve the cloud provider kind startup latency by polling the endpoints of the apiserver in parallel instead of serial
Fixes: https://github.com/kubernetes-sigs/cloud-provider-kind/issues/185
FYI @slartibart70
> Improve startup latency

- pkg/loadbalancer/server.go
- pkg/loadbalancer/server_test.go
`docker inspect -f {{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}} kindccm-RZTQCN5REF5VESVEBSRFF5NKA2S54JVJFWGT3EOM , with kindccm-... the current container (we should replace such long string for something shorter)`
Fixes: #190
> Use a shorter hash for the container name

- README.md
This patch adds a section to the README describing how to use Podman with `cloud-provider-kind`. Podman does not allow sharing the host networking or binding to privileged ports so the `-enable-lb-port-mapping` option can be used to get an ephemeral port on the host that maps to the `LoadBalancer` listening port.
> docs: describe how to use podman with kind

- pkg/loadbalancer/address_darwin.go
- pkg/loadbalancer/address_other.go
- pkg/loadbalancer/address_windows.go
- pkg/loadbalancer/server.go
- pkg/loadbalancer/tunnel.go
This might be the fix for https://github.com/kubernetes-sigs/cloud-provider-kind/issues/189 or https://github.com/kubernetes-sigs/cloud-provider-kind/issues/192
> If the IP is on the lo device already don't fail

- README.md
Add the macOS `brew install` method in README.md
I also added some headers that need to be reviewed and fixed.
Fixed #208
Wait for homebrew-core merged: https://github.com/Homebrew/homebrew-core/pull/206262
> Update install description in README.md

- .github/workflows/release.yml
partially mitigates: https://arstechnica.com/information-technology/2025/03/supply-chain-attack-exposing-credentials-affects-23k-users-of-tj-actions/
upgrades are still risky, and I did not go through the rest of the actions
> pin release actions by commit

- pkg/container/container.go
- pkg/loadbalancer/proxy.go
- pkg/loadbalancer/tunnel.go
We were only tunneling TCP but seems UDP is also a requested feature
> make loadbalancer tunnel protocol aware

- .github/workflows/bats.yml
- .github/workflows/k8s.yml
- examples/loadbalancer_udp_tcp.yaml
- pkg/loadbalancer/tunnel.go
- tests/README.md
- tests/setup_suite.bash
- tests/tests.bats
Allow to forward UDP on Mac and Windows
Co-author-by: @imchristianlowe
> add bats tests and fix udp on mac and windows

- pkg/loadbalancer/tunnel.go
This change ensures that tunneled TCP connections propagate shut downs when they occur, allowing the opposite party to be signaled appropriately.
A TCP connection can be "half-closed" when `A` shuts down `A->B` by sending a FIN to `B`, and `B` responds with an ACK. The connection becomes "fully-closed" when the same procedure is followed for the `A<-B` direction. When a TCP connection is half-closed in the `A->B` direction, data may continue to flow in the `A<-B` direction.
This signaling exists as a basic function of the TCP protocol, allowing either party to indicate that they are done sending data, and that their peer can finish up as they please. Data can continue to flow in the opposite direction until they are ready to shut down their side of the connection.
When cloud-provider-kind …
> fix(tunnel): propagate half-closed TCP connections

- .github/workflows/gateway.yml
- go.mod
- go.sum
- pkg/gateway/crds/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
- pkg/gateway/crds/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
- pkg/gateway/crds/experimental/gateway.networking.k8s.io_gateways.yaml
- pkg/gateway/crds/experimental/gateway.networking.k8s.io_grpcroutes.yaml
- pkg/gateway/crds/experimental/gateway.networking.k8s.io_httproutes.yaml
- pkg/gateway/crds/experimental/gateway.networking.k8s.io_referencegrants.yaml
- pkg/gateway/crds/experimental/gateway.networking.k8s.io_tcproutes.yaml
- pkg/gateway/crds/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- pkg/gateway/crds/experimental/gateway.networking.k8s.io_udproutes.yaml
- pkg/gateway/crds/experimental/gateway.networking.x-k8s.io_xbackendtrafficpolicies.yaml
- pkg/gateway/crds/experimental/gateway.networking.x-k8s.io_xlistenersets.yaml
- pkg/gateway/crds/experimental/gateway.networking.x-k8s.io_xmeshes.yaml
- pkg/gateway/crds/standard/gateway.networking.k8s.io_backendtlspolicies.yaml
- pkg/gateway/crds/standard/gateway.networking.k8s.io_gatewayclasses.yaml
- pkg/gateway/crds/standard/gateway.networking.k8s.io_gateways.yaml
- pkg/gateway/crds/standard/gateway.networking.k8s.io_grpcroutes.yaml
- pkg/gateway/crds/standard/gateway.networking.k8s.io_httproutes.yaml
- pkg/gateway/crds/standard/gateway.networking.k8s.io_referencegrants.yaml
Updates all go modules using `go get -u` and `go mod tidy`.
Updates to latest CRDs using the `hack/download-gateway-crds.sh` script
Updates GitHub workflow to use the v1.4.0 version.
> Update gateway api to v1.4.0
